package cat.cercavila.cvapi.digitalProducts.application.service;

import cat.cercavila.cvapi.digitalProducts.application.port.in.list.DigitalProductListing;
import cat.cercavila.cvapi.digitalProducts.domain.DigitalProducts;

public class MapperDigitalProductDigitalProductListing {
    public static DigitalProducts figuraListingToFigura (DigitalProductListing digitalProductListing) {
        DigitalProducts figura = new DigitalProducts(digitalProductListing.name(), digitalProductListing.year(), digitalProductListing.type(), digitalProductListing.imageKey(), digitalProductListing.webUrl());
        // NOTE: We don't set the id because it is autogenerated by the database
        return figura;
    }

    public static DigitalProductListing figuraToFiguraListing (DigitalProducts figura, byte[] image) {
        DigitalProductListing digitalProductListing = new DigitalProductListing(figura.getId(), figura.getName(), figura.getYear(), figura.getType(),  figura.getImageKey(), image, figura.getWebUrl());
        return digitalProductListing;
    }
}