package cat.cercavila.cvapi.digitalProducts.application.service;

import cat.cercavila.cvapi.digitalProducts.application.port.in.list.DigitalProductListing;
import cat.cercavila.cvapi.digitalProducts.domain.DigitalProduct;

public class MapperDigitalProductDigitalProductListing {
    public static DigitalProduct digitalProductListingToDigitalProduct(DigitalProductListing digitalProductListing) {
        DigitalProduct digitalProduct = new DigitalProduct(digitalProductListing.name(), digitalProductListing.description(),
                digitalProductListing.imageKey(), digitalProductListing.primaryColour(), digitalProductListing.secondaryColour(), digitalProductListing.price(), digitalProductListing.type());
        // NOTE: We don't set the id because it is autogenerated by the database
        return digitalProduct;
    }

    public static DigitalProductListing digitalProductToDigitalProductListing(DigitalProduct digitalProduct, byte[] image) {
        DigitalProductListing digitalProductListing = new DigitalProductListing(digitalProduct.getId(), digitalProduct.getName(), digitalProduct.getDescription(),
                digitalProduct.getImageKey(), image, digitalProduct.getPrimaryColour(), digitalProduct.getSecondaryColour(), digitalProduct.getPrice(), digitalProduct.getType());
        return digitalProductListing;
    }
}