package cat.cercavila.cvapi.activities.application.service;

import cat.cercavila.cvapi.activities.application.port.in.list.ActivityListing;
import cat.cercavila.cvapi.activities.domain.Activity;

public class MapperActivityActivityListing {
    public static Activity figuraListingToFigura (ActivityListing activityListing) {
        Activity activity = new Activity(activityListing.name(), activityListing.year(), activityListing.type(), activityListing.imageKey(), activityListing.webUrl());
        // NOTE: We don't set the id because it is autogenerated by the database
        return activity;
    }

    public static ActivityListing figuraToFiguraListing (Activity activity, byte[] image) {
        ActivityListing activityListing = new ActivityListing(activity.getId(), activity.getQuestion(), activity.getYear(), activity.getType(),  activity.getImageKey(), image, activity.getCorrectAnswer());
        return activityListing;
    }
}