package cat.cercavila.cvapi.colles.application.service;

import cat.cercavila.cvapi.colles.application.port.in.list.CollaListing;
import cat.cercavila.cvapi.colles.domain.Colla;
import org.springframework.web.multipart.MultipartFile;

public class MapperCollaCollaListing {
    public static Colla collaListingToColla (CollaListing collaListing) {
        Colla colla = new Colla(collaListing.name(), collaListing.entity(), collaListing.foundationYear(), collaListing.description(), collaListing.type(), collaListing.neighbourhood(),
                collaListing.primaryColour(), collaListing.secondaryColour(), collaListing.logoKey(), collaListing.music(), collaListing.email(), collaListing.instagram(), collaListing.figures());
        // NOTE: We don't set the id because it is autogenerated by the database
        return colla;
    }

    public static CollaListing collaToCollaListing (Colla colla, byte[] logo) {
        CollaListing collaListing = new CollaListing(colla.getId(), colla.getName(), colla.getEntity(), colla.getFoundationYear(), colla.getDescription(), colla.getType(), colla.getNeighbourhood(),
                colla.getPrimaryColour(), colla.getSecondaryColour(), colla.getLogoKey(), logo, colla.getMusic(), colla.getEmail(), colla.getInstagram(), colla.getFigures());
        return collaListing;
    }
}