package cat.cercavila.cvapi.users.application.service;

import cat.cercavila.cvapi.users.application.port.in.list.UserListing;
import cat.cercavila.cvapi.users.domain.User;

public class MapperUserUserListing {
    public static User collaListingToColla (UserListing userListing) {
        User user = new User(userListing.name(), userListing.entity(), userListing.foundationYear(), userListing.description(), userListing.type(), userListing.neighbourhood(),
                userListing.primaryColour(), userListing.secondaryColour(), userListing.logoKey(), userListing.music(), userListing.email(), userListing.instagram(), userListing.figures());
        // NOTE: We don't set the id because it is autogenerated by the database
        return user;
    }

    public static UserListing collaToCollaListing (User user, byte[] logo) {
        UserListing userListing = new UserListing(user.getId(), user.getName(), user.getEntity(), user.getFoundationYear(), user.getDescription(), user.getType(), user.getNeighbourhood(),
                user.getPrimaryColour(), user.getSecondaryColour(), user.getLogoKey(), logo, user.getMusic(), user.getEmail(), user.getInstagram(), user.getFigures());
        return userListing;
    }
}