package cat.cercavila.cvapi.users.application.service;

import cat.cercavila.cvapi.users.application.port.in.list.UserListing;
import cat.cercavila.cvapi.users.domain.User;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapperUserUserListing {
    public static User userListingToUser (UserListing userListing) {
        List<String> roles = stringToListString(userListing.roles());
        List<String> digitalProducts = stringToListString(userListing.digitalProducts());
        List<String> activePins = stringToListString(userListing.activePins());

        User user = new User(userListing.nickname(), userListing.name(), userListing.firstSurname(), userListing.secondSurname(), userListing.email(), userListing.password(), roles,
            userListing.coins(), digitalProducts, userListing.activeUserImage(), userListing.activeUserImageFrame(), userListing.activeUserBackgroundImage(), userListing.activeUserTitle(),
            userListing.activeUserBackgroundColour(), activePins);
        // NOTE: We don't set the id because it is autogenerated by the database
        return user;
    }

    public static UserListing userToUserListing (User user) {
        String roles = listStringToString(user.getRoles());
        String digitalProducts = listStringToString(user.getDigitalProducts());
        String activePins = listStringToString(user.getActivePins());

        UserListing userListing = new UserListing(user.getId(), user.getNickname(), user.getName(), user.getFirstSurname(), user.getSecondSurname(), user.getEmail(), user.getPassword(), roles,
                user.getCoins(), digitalProducts, user.getActiveUserImage(), user.getActiveUserImageFrame(), user.getActiveUserBackgroundImage(), user.getActiveUserTitle(),
                user.getActiveUserBackgroundColour(), activePins);
        return userListing;
    }

    private static String listStringToString(List<String> list) { return list.stream().collect(Collectors.joining(",")); }
    private static List<String> stringToListString(String string) {
        return Arrays.asList(string.split(","));
    }
}