package cat.cercavila.cvapi.users.application.service;

import cat.cercavila.cvapi.users.application.port.in.list.UserListing;
import cat.cercavila.cvapi.users.domain.User;

public class MapperUserUserListing {
    public static User collaListingToColla (UserListing userListing) {
        User user = new User(userListing.nickname(), userListing.name(), userListing.firstSurname(), userListing.secondSurname(), userListing.email(), userListing.password(), userListing.roles(),
            userListing.coins(), userListing.digitalProducts(), userListing.activeUserImage(), userListing.activeUserImageFrame(), userListing.activeUserBackgroundImage(), userListing.activeUserTitle(),
            userListing.activeUserBackgroundColour(), userListing.activePins());
        // NOTE: We don't set the id because it is autogenerated by the database
        return user;
    }

    public static UserListing collaToCollaListing (User user) {
        UserListing userListing = new UserListing(user.getId(), user.getNickname(), user.getName(), user.getFirstSurname(), user.getSecondSurname(), user.getEmail(), user.getPassword(), user.getRoles(),
                user.getCoins(), user.getDigitalProducts(), user.getActiveUserImage(), user.getActiveUserImageFrame(), user.getActiveUserBackgroundImage(), user.getActiveUserTitle(),
                user.getActiveUserBackgroundColour(), user.getActivePins());
        return userListing;
    }
}