package cat.cercavila.cvapi.event.application.service;

import cat.cercavila.cvapi.event.domain.Event;
import cat.cercavila.cvapi.event.application.port.in.list.EventListing;

public class MapperEventEventListing {
    public static Event eventListingToEvent(EventListing eventListing) {
        Event event = new Event(eventListing.name(), eventListing.description(),
                eventListing.imageKey(), eventListing.primaryColour(), eventListing.secondaryColour(), eventListing.price(), eventListing.type());
        // NOTE: We don't set the id because it is autogenerated by the database
        return event;
    }

    public static EventListing eventToEventListing(Event event, byte[] image) {
        EventListing eventListing = new EventListing(event.getId(), event.getName(), event.getDescription(),
                event.getImageKey(), image, event.getPrimaryColour(), event.getSecondaryColour(), event.getPrice(), event.getType());
        return eventListing;
    }
}