package cat.cercavila.cvapi.events.application.service;

import cat.cercavila.cvapi.events.domain.Event;
import cat.cercavila.cvapi.events.application.port.in.list.EventListing;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapperEventEventListing {
    public static Event eventListingToEvent(EventListing eventListing) {
        List<String> cercatrivies = stringToListString(eventListing.cercatrivies());
        List<String> firstDigitalProductsReward = stringToListString(eventListing.firstDigitalProductsReward());
        List<String> secondDigitalProductsReward = stringToListString(eventListing.secondDigitalProductsReward());
        List<String> thirdDigitalProductsReward = stringToListString(eventListing.thirdDigitalProductsReward());
        List<String> fourthTenthDigitalProductsReward = stringToListString(eventListing.fourthTenthDigitalProductsReward());
        List<String> allDigitalProductsReward = stringToListString(eventListing.allDigitalProductsReward());

        Event event = new Event(eventListing.name(), eventListing.description(), eventListing.imageKey(),
                eventListing.primaryColour(), eventListing.secondaryColour(), eventListing.type(),
                eventListing.startDate(), eventListing.endDate(), cercatrivies, eventListing.firstCoinsReward(), firstDigitalProductsReward,
                eventListing.secondCoinsReward(), secondDigitalProductsReward, eventListing.thirdCoinsReward(), thirdDigitalProductsReward,
                eventListing.fourthTenthCoinsReward(), fourthTenthDigitalProductsReward, eventListing.allCoinsReward(), allDigitalProductsReward);
        // NOTE: We don't set the id because it is autogenerated by the database
        return event;
    }

    public static EventListing eventToEventListing(Event event, byte[] image) {
        String cercatrivies = listStringToString(event.getCercatrivies());
        String firstDigitalProductsReward = listStringToString(event.getFirstDigitalProductsReward());
        String secondDigitalProductsReward = listStringToString(event.getSecondDigitalProductsReward());
        String thirdDigitalProductsReward = listStringToString(event.getThirdDigitalProductsReward());
        String fourthTenthDigitalProductsReward = listStringToString(event.getFourthTenthDigitalProductsReward());
        String allDigitalProductsReward = listStringToString(event.getAllDigitalProductsReward());

        EventListing eventListing = new EventListing(event.getId(), event.getName(), event.getDescription(),
                event.getImageKey(), image, event.getPrimaryColour(), event.getSecondaryColour(), event.getType(),
                event.getStartDate(), event.getEndDate(), cercatrivies, event.getFirstCoinsReward(), firstDigitalProductsReward,
                event.getSecondCoinsReward(), secondDigitalProductsReward, event.getThirdCoinsReward(), thirdDigitalProductsReward,
                event.getFourthTenthCoinsReward(), fourthTenthDigitalProductsReward, event.getAllCoinsReward(), allDigitalProductsReward);
        return eventListing;
    }

    private static String listStringToString(List<String> list) { return list.stream().collect(Collectors.joining(",")); }
    private static List<String> stringToListString(String string) {
        return Arrays.asList(string.split(","));
    }
}